# Login Locators
Username_Locator = "//input[@id='login_email']"
password_Locator = "//input[@id='login_password']"
Login_Button = "//button[@type='submit']"
Success_Login = "//input[@id='navbar-search']"
Institution_title = "//h3[@title='New Institution']"

#  Links Locators
Academic_Structure = "//a[@href='/app/academic-structure']"
Admission = "//a[@href='/app/admission']"
Institution_Link = "//a[@href='/app/institution']"
Campuses_Link = "//a[@href='/app/campus']"
College_Link =  "//a[@href='/app/college']"
Academic_Program_Link = "//a[@href='/app/academic-program']"

# Institutions Locators 
Add_Inistitutions = "//span[@data-label='Add%20Institution']"
Institution_Code_Locator = "//input[@data-fieldname='institution_code']"
Institution_Name_Locator = "//input[@data-fieldname='institution_name']"
Institutional_Type_Locator ="//input[@data-fieldname='institutional_type']"
Institutional_Type_Selected = "//ul[@id='awesomplete_list_4']/li[1]"
Website_Locator = "//input[@data-fieldname='website']"
Email_Locator = "//input[@data-fieldname='email']"
Ownership_Locator = "//input[@data-fieldname='ownership']"
Ownership_Selected = "//ul[@id='awesomplete_list_5']/li[1]"
Location_Locator = "//input[@data-fieldname='location'][@data-doctype='Institution']"
MOE_Number_Locator = "//input[@data-fieldname='moe_number']"
Time_Zone_Locator = "//select[@data-fieldname='time_zone']"
Time_Zone_Selected = "//select[@data-fieldname='time_zone']/option[1]"
Date_of_establishment_Locator = "//input[@data-fieldname='establishment_date']"
Date_of_establishment_date = "//div[@id='datepickers-container']/div/div[1]/div/div[2]/div[3]"
Submit_Institution = "//button[@data-label='Save']"
Successfully_Saved = "//*[@id='alert-container']"

# Campuses Locators 
Add_Campuses = "//span[@data-label='Add%20Campus']"
Campus_name_Locator = "/html/body/div[5]/div/div/div[2]/div[1]/div/div[2]/div/div/div/form/div[1]/div/div[2]/div[1]/input"
campus_code_Locator = "/html/body/div[5]/div/div/div[2]/div[1]/div/div[2]/div/div/div/form/div[2]/div/div[2]/div[1]/input"
campus_location_Locator = "/html/body/div[5]/div/div/div[2]/div[1]/div/div[2]/div/div/div/form/div[3]/div/div[2]/div[1]/input"
Submit_Campus = "/html/body/div[8]/div/div/div[3]/div[2]/button[2]"

# Colleges Locators 
Add_College = "//span[@data-label='Add%20College']"
College_Name_Locator = "//input[@data-fieldname='college_name'][@data-doctype='College']"
College_Code_Locator = "//input[@data-fieldname='college_code'][@data-doctype='College']"
Establishment_date_Locator = "//input[@data-fieldname='establishment_date']"
Establishment_date = "//*[@id='datepickers-container']/div/div[1]/div/div[2]/div[4]"
Open_campus_collapse = "//DIV[@class='section-head collapsed']"
Add_capmus_row = "//button[@class='btn btn-xs btn-secondary grid-add-row']"
click_in_campus_row = "(//DIV[@class='col grid-static-col col-xs-10 '])[2]"
Select_campus = "//P[@title='1']"
Submit_college = "//*[@id='page-College']/div[1]/div/div/div[2]/div[3]/button[2]/span"

# Academic Program Locators
Add_Academic_Program = "//span[@data-label='Add%20Academic%20Program']"
Program_Name_Locator = "//*[@id='page-Academic Program']/div[2]/div[2]/div/div[3]/div[2]/div[1]/div[2]/div/div/div[3]/div[1]/div/div[1]/form/div[2]/div/div[2]/div[1]/input"
Program_Code_Locator  = "//*[@id='page-Academic Program']/div[2]/div[2]/div/div[3]/div[2]/div[1]/div[2]/div/div/div[3]/div[1]/div/div[2]/form/div/div/div[2]/div[1]/input" 
Status_Locator  = "//Select[@data-fieldname='status']" 
Status_Option_Locator  = "//Select[@data-fieldname='status']/option[1]"
Major_Locator  = "//div[@data-fieldname='major']//div[@class='form-group']//input[@role='combobox']" 
Major_Option_Locator = "//*[@id='awesomplete_list_4']/li[1]"
Education_level_Locator  = "//input[@data-fieldname='education_level']" 
Education_level_Option_Locator = "//ul[@id='awesomplete_list_6']/li[1]"
Degree_Locator  = "//input[@data-fieldname='degree']"
Degree_Option_Locator = "//ul[@id='awesomplete_list_20']/li[1]"
Scientific_Certificate_Locator  = "//input[@data-fieldname='scientific_certificate']"
Scientific_Certificate_Option_Locator = "//ul[@id='awesomplete_list_18']/li[1]"
Add_Ownership_Button = "//div[@data-fieldname='offerings']//button[@class='btn btn-xs btn-secondary grid-add-row']"
Ownership_Campus_Locator = "//input[@data-fieldname='campus']"
Ownership_Campus__Option_Locator = "//ul[@id='awesomplete_list_16']/li/a/p[@title='Arar'']"
Ownership_College_Locator = "//input[@data-fieldname='college']"
Ownership_College_Option_Locator = "//ul[@id='awesomplete_list_26']/li[1]"
Ownership_Department_Locator = "//input[@data-fieldname='department']"
Ownership_Department_Option_Locator = "//ul[@id='awesomplete_list_27']/li[1]"
Add_Tracks_Button = ""
Track_Name_Locator = ""
Student_Gender_Locator = ""
Qualification_Level_Locator = ""
Period_Type_Locator = ""
Program_Type_Locator = ""
Mode_of_Instruction_Locator = ""
Periods_to_complete_the_program_Locator = ""
Program_Language_Locator = ""
Maximum_Terms_to_complete_the_program_Locator = ""
Program_Discipline_Domain_Locator = ""
Study_Start_Date_Locator = ""
Total_Credit_Hours_Locator = ""
Current_capacity_Locator = ""
Web_View_Section_Name_Locator = ""
Add_Section_Name_Button = ""
Web_View_Section_MyField_Locator = ""
Web_View_Section_Camp_Locator = ""

